class FindFailed(BaseException):
    pass


class SolvingError(BaseException):
    pass


class Solved(BaseException):
    pass
